FROM ubuntu:20.04
# Who is responsible for what
LABEL maintainer="Lovisa Nguyen" email="lovisa.nguyen@proton.fi"
# Next, can be: RUN, INSTALL, EXCUTE
RUN echo "hello world" >> helloworld.txt
RUN cat helloworld.txt 
